name: royal_reels
description: "A new Flutter project."
publish_to: "none"
version: 7.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.2.3
  # extended_wrap: ^0.1.5
  another_flushbar: ^1.12.30
  # shimmer: ^3.0.0
  go_router: ^12.1.1
  #!
  get_it: ^7.6.0
  equatable: ^2.0.5
  # flutter_secure_storage: ^8.0.0
  google_fonts: ^6.1.0
  url_launcher: ^6.1.11
  intl: ^0.18.1
  injectable: ^2.1.2
  flutter_localizations:
    sdk: flutter
  # dynamic_height_grid_view: ^0.0.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^1.0.3
  rate_my_app: ^2.0.0
  carousel_slider: ^4.2.1
  image_picker: ^1.0.7

  xml: ^6.5.0
  dio: ^5.4.0
  webview_flutter: ^4.7.0
  flutter_native_splash: ^2.3.11

flutter_native_splash:
  ios: true
  color: "#1A1B20"
  image: "assets/images/royal_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/Poppins/
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/images/royal_reels_lvl_cards/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_icon.png"
  min_sdk_android: 21
